name: Subgraph Dev Deployment

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
    types:
      - closed

jobs:
  deploy:
    env:
      ACCESS_TOKEN_SERVICE: ${{ secrets.ACCESS_TOKEN_SERVICE }}
      ACCESS_TOKEN_STUDIO: ${{ secrets.ACCESS_TOKEN_STUDIO }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: yarn

      - run: yarn prepare:goerli
      - run: yarn prepare:optimism-goerli
      - run: yarn prepare:sepolia

      - run: yarn codegen

      - run: yarn auth:service "$ACCESS_TOKEN_SERVICE"
      - run: yarn build:goerli && yarn deploy:goerli && yarn deploy:goerli-alpha
      - run: yarn build:optimism-goerli && yarn deploy:optimism-goerli

      - name: Fetch tags
        run: git fetch --tags

      - name: Determine current version
        id: versioning
        run: |
          CURRENT_VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "1.0.2")
          echo "Current version: $CURRENT_VERSION"

      - name: Bump version
        id: bump_version
        run: |
          NEW_VERSION="${{ steps.versioning.outputs.CURRENT_VERSION }}+1"
          echo "New version: $NEW_VERSION"

      - name: Create tag
        run: |
          git tag ${{ steps.bump_version.outputs.NEW_VERSION }}
          git push --tags

      - run: yarn auth:studio "$ACCESS_TOKEN_STUDIO"
      - run: yarn build:sepolia && yarn deploy:sepolia ${{ steps.bump_version.outputs.NEW_VERSION }}
      
